---
- hosts: all
  tasks:
    - name: ensure ntpd is at the latest version
      yum: pkg=ntp state=latest
      become: True
      become_method: sudo
      notify:
      - restart ntpd
  handlers:
    - name: restart ntpd
      become: True
      become_method: sudo
      service: name=ntpd state=restarted
