---

- name: Install Docker Requirements
  yum: name={{item}} state=present
  with_items:
    - yum-utils
    - device-mapper-persistent-data
    - lvm2

- name: Add Docker yum repository
  yum_repository:
    name: docker-ce
    description: Docker CE
    baseurl: https://download.docker.com/linux/centos/docker-ce.repo

- name: Install Docker
  yum:
    name: docker-ce
    state: present
    update_cache: True